### ISSUE TITLE
Add a menu

### ISSUE THREAD

**Issue by bmicallef1** [bmicallef1/Exercise-Python#1]
**User Story**

As a user I would like to be able use a menu in order to navigate the program more easily.

* Persona: User who wants to navigate the program easily.
* Feature: The user can enter the whatever option they want's on the menu.
* Business Value: Due to the simplicity, errors are less likely to occur.

**Description**
A menu is created contain the different options the user can use.

**Task List**
- [x] create an if statement so the user can quit the menu.
- [x] if an invalid option is entered the user can enter another option.
- [x] The menu is formatted in a nice way.

**Acceptance Criteria**
1. Will loop until user exits.
2. Invalid options don't ruin program.

**Acceptance Test**
1. The user should be able to exit the menu with "q" (not case sensitive).
2. If the user enters an invalid option, the menu will re-appear for the user to enter again.
