### ISSUE TITLE
List all the movie names

### ISSUE THREAD

**Issue by bmicallef1** [bmicallef1/Exercise-Python#3]
**User Story**

As a user I would like the option to display all the available movies in the program.

* Persona: User who wants to view all movies.
* Feature: The user will be shown all available movies.
* Business Value: Users will not have to request for a list of all movie names, they can look it up themself.

**Description**
An option will be added that allows the user to view every movie name that is on record.

**Task List**
- [x] Add an option (list) to show all movie names.
- [x] Each movie is displayed on there own individual line.
- [x] A number of the movie is displayed next to the movie.

**Acceptance Criteria**
1. Displays all movies.
2. Does not display the movie cast.

**Acceptance Test**
1. All the movies that are on record will be displayed to the user.
2. Each movie name is displayed on a separate line.
3. The number of the movie in the list is displayed next to the movie name.
